spring:
  application:
      name: microservice-zuul-gateway
server:
  port: 9527
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  routes:
    gouwuEmployee.serviceId: employee-provider
    gouwuEmployee.path: /employee/**  # 匹配 /xxx开头的请求映射到user-provider服务上

    gouwuProduct.serviceId: gouwu-product
    gouwuProduct.path: /product/**  # 匹配 /xxx开头的请求映射到user-provider服务上

    gouwuCommon.serviceId: common-privoder
    gouwuCommon.path: /common/**
  ignored-services: "*" #user-provider #忽略直接使用服务名访问  *忽略所有的
  prefix: /gouwu   # 访问前缀