server:
  port: 8002
spring:
  application:
    name: GOUWU-PRODUCT
  datasource:  #数据库的配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gouwu?useUnicode=true&characterEncoding=UTF-8  #防止中文乱码
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:cn/itsource/gouwu/mapper/*Mapper.xml #扫mapper映射
  type-aliases-package: cn.itsource.gouwu.domain,cn.itsource.gouwu.query  #别名的配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true